#Minecraft server properties
#Thu Jan 28 22:45:38 CST 2016
generator-settings=
op-permission-level=4
allow-nether=true
level-name=world
enable-query=false
allow-flight=true
announce-player-achievements=false
server-port=25565
level-type=DEFAULT
enable-rcon=false
force-gamemode=false
level-seed=
server-ip=
max-build-height=256
spawn-npcs=true
white-list=true
debug=false
spawn-animals=true
snooper-enabled=true
hardcore=false
online-mode=true
resource-pack=
pvp=true
difficulty=1
enable-command-block=false
server-name=LegacyHCF
player-idle-timeout=0
gamemode=0
max-players=250
spawn-monsters=true
view-distance=10
generate-structures=true
spawn-protection=16
motd=\u00A76\u00A7lLegacyHCF\u00A78 \u00BB \u00A76The Unique PvP Server\n\u00A7aNEWS\u00A78 \u00BB \u00A7cSee you tonight at 5PM EST\!
